-- ============================================
-- סקריפט שחזור מלא של מבנה הדאטהבייס
-- תאריך: 06.02.2025
-- ============================================

-- 1. יצירת טבלת spots (מקומות)
create table if not exists public.spots (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  address text not null,
  latitude double precision not null,
  longitude double precision not null,
  category text not null check (category in ('מסעדה', 'בית קפה', 'בר', 'אטרקציה', 'טבע', 'אחר')),
  price_range text not null check (price_range in ('חינם', 'זול', 'בינוני', 'יקר')),
  kosher_type text check (kosher_type in ('מהדרין', 'רבנות', '?')),
  kosher_certificate text,
  noise_level text not null check (noise_level in ('שקט', 'בינוני', 'רועש')),
  region text not null check (region in ('ירושלים', 'מרכז', 'צפון', 'דרום')),
  suitable_for_first_date boolean not null default false,
  parking_available boolean not null default false,
  public_transport boolean not null default false,
  reservation_required boolean not null default false,
  opening_hours text,
  recommended_time text,
  notes text,
  phone text,
  website text,
  images text[],
  average_rating double precision,
  status text default 'active' check (status in ('active', 'under_review', 'blocked')),
  created_at timestamptz default timezone('utc'::text, now())
);

-- אינדקסים לטבלת spots
create index if not exists spots_category_idx on public.spots(category);
create index if not exists spots_region_idx on public.spots(region);
create index if not exists spots_status_idx on public.spots(status);
create index if not exists spots_location_idx on public.spots using gist (point(longitude, latitude));

-- 2. יצירת טבלת reviews (ביקורות)
create table if not exists public.reviews (
  id uuid default uuid_generate_v4() primary key,
  spot_id uuid not null references public.spots(id) on delete cascade,
  reviewer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  content text not null,
  visit_date date,
  created_at timestamptz default timezone('utc'::text, now())
);

-- אינדקסים לטבלת reviews
create index if not exists reviews_spot_id_idx on public.reviews(spot_id);
create index if not exists reviews_created_at_idx on public.reviews(created_at);

-- 3. יצירת טבלת reports (דיווחים)
create table if not exists public.reports (
  id uuid default uuid_generate_v4() primary key,
  spot_id uuid not null references public.spots(id) on delete cascade,
  report_type text not null check (report_type in ('spam', 'inappropriate', 'closed', 'duplicate', 'other')),
  description text not null,
  reporter_ip text not null,
  status text default 'pending' check (status in ('pending', 'in_review', 'resolved', 'rejected')),
  admin_notes text,
  created_at timestamptz default timezone('utc'::text, now()),
  updated_at timestamptz default timezone('utc'::text, now())
);

-- אינדקסים לטבלת reports
create index if not exists reports_spot_id_idx on public.reports(spot_id);
create index if not exists reports_status_idx on public.reports(status);
create index if not exists reports_created_at_idx on public.reports(created_at);

-- 4. יצירת טבלת logs (לוגים)
create table if not exists public.logs (
  id uuid default uuid_generate_v4() primary key,
  type text not null,
  data jsonb,
  severity text default 'info' check (severity in ('info', 'warning', 'error')),
  timestamp timestamptz default timezone('utc'::text, now()),
  ip_address text,
  user_agent text
);

-- אינדקסים לטבלת logs
create index if not exists logs_timestamp_idx on public.logs(timestamp);
create index if not exists logs_type_idx on public.logs(type);
create index if not exists logs_severity_idx on public.logs(severity);

-- 5. יצירת טבלת rate_limits (מגבלות קצב)
create table if not exists public.rate_limits (
  id bigint generated by default as identity primary key,
  key text not null unique,
  attempts integer not null default 0,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- אינדקסים לטבלת rate_limits
create index if not exists rate_limits_expires_idx on public.rate_limits(expires_at);
create index if not exists rate_limits_key_idx on public.rate_limits(key);

-- 6. יצירת טבלת admin_ips (כתובות IP מורשות למנהלים)
create table if not exists public.admin_ips (
  id uuid default uuid_generate_v4() primary key,
  ip text not null unique,
  description text,
  is_active boolean default true,
  created_at timestamptz default timezone('utc'::text, now())
);

-- אינדקסים לטבלת admin_ips
create index if not exists admin_ips_ip_idx on public.admin_ips(ip);
create index if not exists admin_ips_active_idx on public.admin_ips(is_active);

-- ============================================
-- פונקציות
-- ============================================

-- פונקציה לעדכון updated_at
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql security definer;

-- פונקציה לניקוי רשומות rate_limits שפג תוקפן
create or replace function public.cleanup_expired_rate_limits()
returns void as $$
begin
  delete from public.rate_limits
  where expires_at < now();
end;
$$ language plpgsql security definer;

-- פונקציה לטריגר שמפעיל את הניקוי
create or replace function public.trigger_cleanup_expired_rate_limits()
returns trigger as $$
begin
  perform public.cleanup_expired_rate_limits();
  return new;
end;
$$ language plpgsql security definer;

-- פונקציה לקבלת כתובת ה-IP של הלקוח
create or replace function public.get_client_ip()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  return jsonb_build_object(
    'client_ip',
    current_setting('request.headers')::jsonb->>'x-real-ip'
  );
end;
$$;

-- פונקציה לבדיקת גישת מנהל לפי IP
create or replace function public.check_admin_access(client_ip text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  ip_to_check text;
begin
  -- אם לא סופק IP, ננסה לקבל אותו מההקשר
  if client_ip is null then
    ip_to_check := current_setting('request.headers')::jsonb->>'x-real-ip';
  else
    ip_to_check := client_ip;
  end if;
  
  -- בדיקה אם ה-IP נמצא ברשימת המנהלים הפעילים
  return exists (
    select 1 from public.admin_ips
    where ip = ip_to_check
    and is_active = true
  );
end;
$$;

-- פונקציה לעדכון average_rating של מקום
create or replace function public.update_spot_rating()
returns trigger as $$
begin
  update public.spots
  set average_rating = (
    select avg(rating)::double precision
    from public.reviews
    where spot_id = new.spot_id
  )
  where id = new.spot_id;
  return new;
end;
$$ language plpgsql;

-- ============================================
-- טריגרים
-- ============================================

-- טריגר לעדכון updated_at בטבלת reports
drop trigger if exists update_reports_updated_at on public.reports;
create trigger update_reports_updated_at
  before update on public.reports
  for each row
  execute function public.update_updated_at_column();

-- טריגר לניקוי אוטומטי של rate_limits
drop trigger if exists auto_cleanup_rate_limits on public.rate_limits;
create trigger auto_cleanup_rate_limits
  after insert or update on public.rate_limits
  for each statement
  execute function public.trigger_cleanup_expired_rate_limits();

-- טריגר לעדכון דירוג ממוצע אחרי הוספת/עדכון ביקורת
drop trigger if exists update_spot_rating_trigger on public.reviews;
create trigger update_spot_rating_trigger
  after insert or update or delete on public.reviews
  for each row
  execute function public.update_spot_rating();

-- ============================================
-- Row Level Security (RLS)
-- ============================================

-- הפעלת RLS על כל הטבלאות
alter table public.spots enable row level security;
alter table public.reviews enable row level security;
alter table public.reports enable row level security;
alter table public.logs enable row level security;
alter table public.rate_limits enable row level security;
alter table public.admin_ips enable row level security;

-- מדיניויות לטבלת spots
drop policy if exists "Enable read access for all users" on public.spots;
drop policy if exists "Enable insert access for all users" on public.spots;
drop policy if exists "Enable update access for all users" on public.spots;

create policy "Enable read access for all users"
on public.spots for select
to anon, authenticated
using (status in ('active', 'under_review'));

create policy "Enable insert access for all users"
on public.spots for insert
to anon, authenticated
with check (true);

create policy "Enable update access for all users"
on public.spots for update
to anon, authenticated
using (true)
with check (true);

-- מדיניויות לטבלת reviews
drop policy if exists "Enable read access for all users" on public.reviews;
drop policy if exists "Enable insert access for all users" on public.reviews;

create policy "Enable read access for all users"
on public.reviews for select
to anon, authenticated
using (true);

create policy "Enable insert access for all users"
on public.reviews for insert
to anon, authenticated
with check (true);

-- מדיניויות לטבלת reports
drop policy if exists "Enable read access for all users" on public.reports;
drop policy if exists "Enable insert access for all users" on public.reports;
drop policy if exists "Enable update access for all users" on public.reports;

create policy "Enable read access for all users"
on public.reports for select
to anon, authenticated
using (true);

create policy "Enable insert access for all users"
on public.reports for insert
to anon, authenticated
with check (true);

create policy "Enable update access for all users"
on public.reports for update
to anon, authenticated
using (true)
with check (true);

-- מדיניויות לטבלת logs
drop policy if exists "Enable insert access for all users" on public.logs;

create policy "Enable insert access for all users"
on public.logs for insert
to anon, authenticated
with check (true);

-- מדיניויות לטבלת rate_limits
drop policy if exists "Enable read access for all users" on public.rate_limits;
drop policy if exists "Enable insert access for all users" on public.rate_limits;
drop policy if exists "Enable update access for all users" on public.rate_limits;
drop policy if exists "Enable delete access for all users" on public.rate_limits;

create policy "Enable read access for all users"
on public.rate_limits for select
to anon, authenticated
using (true);

create policy "Enable insert access for all users"
on public.rate_limits for insert
to anon, authenticated
with check (true);

create policy "Enable update access for all users"
on public.rate_limits for update
to anon, authenticated
using (true)
with check (true);

create policy "Enable delete access for all users"
on public.rate_limits for delete
to anon, authenticated
using (true);

-- מדיניויות לטבלת admin_ips (רק קריאה)
drop policy if exists "Enable read access for all users" on public.admin_ips;

create policy "Enable read access for all users"
on public.admin_ips for select
to anon, authenticated
using (true);

-- ============================================
-- הרשאות
-- ============================================

grant usage on schema public to anon, authenticated;
grant all on public.spots to anon, authenticated;
grant all on public.reviews to anon, authenticated;
grant all on public.reports to anon, authenticated;
grant all on public.logs to anon, authenticated;
grant all on public.rate_limits to anon, authenticated;
grant select on public.admin_ips to anon, authenticated;

grant execute on function public.cleanup_expired_rate_limits() to anon, authenticated;
grant execute on function public.update_updated_at_column() to anon, authenticated;
grant execute on function public.trigger_cleanup_expired_rate_limits() to anon, authenticated;
grant execute on function public.get_client_ip() to anon, authenticated;
grant execute on function public.check_admin_access(text) to anon, authenticated;
grant execute on function public.update_spot_rating() to anon, authenticated;



