-- מחיקת כל האובייקטים הקיימים
drop trigger if exists auto_cleanup_rate_limits on public.rate_limits;
drop trigger if exists update_rate_limits_updated_at on public.rate_limits;
drop function if exists public.trigger_cleanup_expired_rate_limits();
drop function if exists public.cleanup_expired_rate_limits();
drop function if exists public.update_updated_at_column();
drop function if exists public.get_client_ip();
drop index if exists rate_limits_expires_idx;
drop index if exists rate_limits_key_idx;
drop index if exists rate_limits_key_expires_idx;

-- וידוא שהטבלה קיימת עם המבנה הנכון
drop table if exists public.rate_limits cascade;
create table public.rate_limits (
  id bigint generated by default as identity primary key,
  key text not null unique,
  attempts integer not null default 0,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- פונקציה לקבלת כתובת ה-IP של הלקוח
create function public.get_client_ip()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  return jsonb_build_object(
    'client_ip',
    current_setting('request.headers')::jsonb->>'x-real-ip'
  );
end;
$$;

-- הוספת אינדקס על expires_at לביצועים
create index rate_limits_expires_idx 
  on public.rate_limits(expires_at);

-- וידוא שיש RLS מתאים על הטבלה
alter table public.rate_limits enable row level security;

-- מחיקת מדיניויות קיימות
drop policy if exists "Enable read access for all users" on public.rate_limits;
drop policy if exists "Enable insert access for all users" on public.rate_limits;
drop policy if exists "Enable update access for all users" on public.rate_limits;

-- יצירת מדיניויות חדשות
create policy "Enable read access for all users"
on public.rate_limits for select
to anon, authenticated
using (true);

create policy "Enable insert access for all users"
on public.rate_limits for insert
to anon, authenticated
with check (true);

create policy "Enable update access for all users"
on public.rate_limits for update
to anon, authenticated
using (true)
with check (true);

create policy "Enable delete access for all users"
on public.rate_limits for delete
to anon, authenticated
using (true);

-- הוספת טריגר לעדכון updated_at
create function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql security definer;

create trigger update_rate_limits_updated_at
  before update on public.rate_limits
  for each row
  execute function public.update_updated_at_column();

-- פונקציה לניקוי רשומות ישנות
create function public.cleanup_expired_rate_limits()
returns void as $$
begin
  delete from public.rate_limits
  where expires_at < now();
end;
$$ language plpgsql security definer;

-- פונקציה לטריגר שמפעיל את הניקוי
create function public.trigger_cleanup_expired_rate_limits()
returns trigger as $$
begin
  perform public.cleanup_expired_rate_limits();
  return new;
end;
$$ language plpgsql security definer;

-- הוספת טריגר שמפעיל את הניקוי באופן אוטומטי
create trigger auto_cleanup_rate_limits
  after insert or update on public.rate_limits
  for each statement
  execute function public.trigger_cleanup_expired_rate_limits();

-- הענקת הרשאות
grant usage on schema public to anon, authenticated;
grant all on public.rate_limits to anon, authenticated;
grant execute on function public.cleanup_expired_rate_limits() to anon, authenticated;
grant execute on function public.update_updated_at_column() to anon, authenticated;
grant execute on function public.trigger_cleanup_expired_rate_limits() to anon, authenticated;
grant execute on function public.get_client_ip() to anon, authenticated; 